### ISSUE TITLE
Cannot get ruby-selenium to run with the directions listed.

### ISSUE THREAD

**Issue by tjmaher** [getgauge-examples/gauge-active-admin-example-ruby#2]
Cannot get ruby-selenium to run.

* I cloned the repo to my Windows 10 PC.
* I started up the WAR file of the SUT.

1) With bundle exec gauge specs:
`Error: unknown command "specs" for "gauge"
Run 'gauge --help' for usage.`

2) With bundle exec gauge run specs

`C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find io-like-0.3.0 in any of the sources (Bundler::GemNotFound)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `map!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `materialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:237:in `specs_for'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:226:in `requested_specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:108:in `block in definition_method'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:20:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/setup.rb:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Ruby runner Failed. Reason: exit status 1
Failed to start gauge API: Runner with pid 110912 quit unexpectedly(exit status 1).`

**Comment by sriv** [comment]
Please try running `bundle install` before running `bundle exec gauge run specs`.
